### ISSUE TITLE
Add a license and tag commits.

### ISSUE THREAD

**Issue by Vonfry** [hchunhui/librime-lua#153] opened 2021-12-17 11:15 UTC
I want to pack this package on a distribution. Would you like to add a license and tags?

**Comment by hchunhui** [comment] 2021-12-19 06:39
Sure. I should have done it earlier. It was intended to be merged into librime, but now it's an external project. I will commit the same license as librime.

For tags, what should I do (follow some naming conventions, etc) ? Can you just use the commit id?

**Comment by Vonfry** [comment] 2021-12-19 07:19
> For tags, what should I do (follow some naming conventions, etc) ? Can you just use the commit id?

Commit id can be used. A tag can help bots to check and update
automatically. Tags means stable and commits means unstable. Now I use
commits directly which is not a big issue.

**Comment by hchunhui** [comment] 2021-12-19 07:34
OK. I have commit the license. I will add tags in the future if the project is stable enough.

**Closed** 2021-12-20 10:48 UTC
